import mysql.connector as sql
conn=sql.connect(host = 'localhost',user='root',passwd='saksham3.14',database='MOVIEBOOKING')
c1=conn.cursor()
if conn.is_connected():
    print('successfully connected to database')
else:
    print("error trying to connect to database")
print()
print()
print('\t           )       )        )          *          )        (         )      )              ')
print('\t   (    ( /(    ( /(     ( /(        (  `      ( /(        )\ )   ( /(   ( /(    (  (      ')
print("\t ( )\   )\())   )\())    )\())       )\))(     )\())      (()/(   )\())  )\())   )\))(   ' ")
print('\t )((_) ((_)\   ((_)\   ((_)\       ((_)()\   ((_)\        /(_)) ((_)\  ((_)\   ((_)()\ )  ')
print('\t((_)_    ((_)    ((_)   _((_)      (_()((_)  __ ((_)      (_))    _((_)   ((_)  _(())\_)() ')
print('\t | _ )  / _ \   / _ \  | |/ /       |  \/  | \ \ / /      / __|  | || |  / _ \  \ \((_)/ / ')
print("\t | _ \ | (_) | | (_) | | ' <        | |\/| |  \ V /       \__ \  | __ | | (_) |  \ \/\/ /  ")
print('\t |___/  \___/   \___/  |_|\_\       |_|  |_|   |_|        |___/  |_||_|  \___/    \_/\_/   \n\n')
print()
print()
print ("Enter your choice as 1 or 2")
print ("=======================IMPERIAL THEATRES BOOKING==================")
print ("1.SIGN UP")
print ("2.LOG IN")
print()
print("COST/SEAT= RM 38")
print()
print()
print()
print("\n\t\t\t  +--------------------+")
print("\t\t\t    |     SHOW TIMINGS   |")
print("\t\t\t    |     ---- -------   |")
print("\t\t\t    +--------------------+")
print("\t\t\t    |1. 10:00 AM         |")
print("\t\t\t    |2. 05:00 PM         |")
print("\t\t\t    |3. 08:30 PM         |")
print("\t\t\t    +--------------------+\n")
ans='yes'
while ans=='yes':
    ch = int(input("Enter your choice :"))
    if ch == 1:
        v_fname = input("Enter your first name :")
        v_lname = input("Enter your last name :")
        v_phno = int(input("Enter phone number :"))
        v_userID = input("Enter your userID, customize for yourself:")
        v_userID = v_userID.upper()
        v_passwd = int(input("Enter your passwd (4 digits) :"))
        v_mname = input("Enter the movie name :")
        v_tic = int(input("Enter total tickets :"))
        v_time= input("enter time: ")
        v_snacks = input("Order your snacks :")
        v_ins = "insert into login values( '{}','{}',{},'{}',{},'{}',{},'{}','{}')".format(v_fname,v_lname,v_phno,v_userID,
                                                                                        v_passwd,v_mname,  v_tic, v_time,v_snacks)
        c1.execute(v_ins)
        conn.commit()
        print("*********************TICKET BOOKED***********************")
        print("Thank you for visiting IMPERIAL THEATRES")

    elif ch==2:
        print("############## WELCOME TO THE BOX OFFICE ##################")
        a = input("Enter your first name :")
        b=input("Enter your userID :")
        b=b.upper()
        pswd = int(input("Enter the password :"))
        c = input("Enter your movie name :")
        d = int(input("Enter total tickets :"))
        sks = input(" Order your snacks :")
        upd= "update login set MOVIE=c, TICKETS=d, SNACKS=sks WHERE FIRST_NAME=A AND USERID=b"
        c1.execute(upd)
        conn.commit()
    ans = input('do you wish to continue? type yes else, press any key; ')
print("                                   ________________________  ")
 print("                               _.-'|                     || ")
 print("                           _.-'   ||                     || ")
 print("          ______       _.-'       ||      /\_/\          || ")
 print("         |      |_ _.-'           ||    =( owo )=        || ")
 print('         |      |_|_              ||      )   (  //      || ')
 print('         |______|   `-._          ||     (__ __)//       || ')
 print('            /\\          `-._      ||                     || ')
 print('           /  \\             `-._  ||  ENJOY YOUR MOVIE!  || ')
 print('          /    \\                `-.I_____________________|| ')
 print('         /      \\                 ------------------------ ')
 print('        /________\\___________________/________________\\____')
 print()
 print("                         __________")
 print("                       //^^^^{}^^^^ ")
 print("                     //..@--------@.. ")
 print("                    //&%&%&%&/\&%&%&%& ")
 print("                   ||&%&%&_.'  '._&%&%&|| ")
 print("                   ||&%'''        '''%&|| ")
 print('                   ||&%& THANKS FOR &%&|| ')
 print('                   ||&%&  VISITING! &%&|| ')
 print('                   ||&%&  SEE YOU   &%&|| ')
 print('                   ||&%&   AGAIN :-)&%&|| ')
